### ISSUE TITLE
Allow setting internal slugify options

### ISSUE THREAD

**Issue by jrbarnard** [combine/objection-slugify#6]
E.g, if we want to set the remove regex as per the [docs here](https://www.npmjs.com/package/slugify#options), we can't currently.

Proposed syntax:
```
const slugify = slugifyPlugin({
  sourceField: 'title',
  slugField: 'slug',
  slugifyOptions: {
    remove: /[*+~.()'"!:@]/g,
  },
});
```

I'm happy to do a PR for this if you guys want?

**Comment by calvinl** [comment]
Great idea. Happy to accept a PR!
